---
title: "experiment2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages}
library(tidyr)
library(dplyr)
library(ggplot2)
library(Rmisc)
library(reshape2)
library(plyr)
library(lmerTest)
library(knitr)
library(data.table)
library(effsize)
library(ggrepel)
source("per_setting.R")
source("blcoking_code.R")
```

```{r load variables}

v.dmg=c("expID","theClick","proID","subID","bonus","gender","age","feedback")
v.eve=c("expID","subID","trOrder","trID","trName","obj","time","act","blc","delay")#"expID","subID"
v.jud=c("expID","subID","trOrder","trID","trName","keyStr","keyEdg","keyEdgPos","position","online","time","ansStr","ansEdg","ansEdgPos")#"expID","subID"
v.sti.cycle=c('loop_in3','clock4','clock_out4',
              'clock3','loop_out3','loop_inout4',
              'loop_double_out3','loop_double_out4')
v.sti.exp1=c('loop_in3','clock4','fork3',
             'clock_out4','chain4','clock3',
             'loop_out3','loop_inout4','fork4',
             'colli3','chain3','colli4')
v.sti.uncon=c('uncon4','uncon3')

str_name=c('colli3','chain3','fork3','colli4','chain4','fork4','uncon3','fully3','uncon4','fully4',
           'loop_in3','clock3','loop_out3','loop_inout4','clock4','clock_out4','loop_double_out3','loop_double_out4')
str_node=c(3,3,3,4,4,4,3,3,4,4,
           3,3,3,4,4,4,3,4)
str_belief=c(9,16,12,59,264,30,1,17,1,265,
             37,35,57,3217,1449,1855,59,3233)
str_code=c(49,35,19,3585,1556,74,1,51,1,2580,
           36,39,43,1588,1620,1748,59,1692)

load("DBN.Rdata")
load("exp2_final.Rda")
```

```{r calculating variables}
#total events
df.off=df.off %>% mutate(eve_num=NA)
for (k in 1:nrow(df.off)){
  df= df.eve %>% subset(subID==df.off$subID[k] & trName==df.off$trName[k] & act %in% c(0,1))
  df.off$eve_num[k]=nrow(df)
}

#peak density
df.eve=df.eve %>% mutate(wd=ceiling(time/1000))
df.off=df.off %>% mutate(eve_den=NA)
for (k in 1:nrow(df.off)){
  df= df.eve %>% subset(subID==df.off$subID[k] & trName==df.off$trName[k] & act %in% c(0,1))
  ev=rep(NA,45)
  for (w in 1:45){
    ev[w]=nrow(subset(df,wd<=w & wd>=w-3))
  }
  df.off$eve_den[k]=max(ev)#df_wd$V1
}

#IO accuracy
df.off=df.off %>% mutate(acc_nor=NA,acc_div_nor=NA,ent_nor=NA,cal_cut=NA)
f=list.files(path = 'exp2_nor/',pattern = "\\.Rda$")

for (i in f){
  load(paste('exp2_nor/',i,sep = ""))
  sub=df.jud.nor$subID[1]
  if (!(sub %in% unique(df.off$subID))){next}
  
  df.jud.nor=df.jud.nor[df.jud.nor$wd==45,]
  
  for (k in 1:nrow(df.jud.nor)){
    gd=str_code[which(str_name==df.jud.nor$trName[k])]
    l=which(df.off$trName==df.jud.nor$trName[k] & df.off$subID==df.jud.nor$subID[k]) 
    df.off$acc_nor[l]=df.jud.nor$acc_nor[k]%>% as.numeric() %>% round(2)
    df.off$acc_div_nor[l]=df.jud.nor$acc_div_nor[k] %>% as.numeric() %>% round(2)
    df.off$ent_nor[l]=df.jud.nor$ent_nor[k] %>% as.numeric() %>% round(2)
    df.off$cal_cut[l]=df.jud.nor$cal_cut[k] %>% as.numeric()
    
    if (df.off$cal_cut[l]!=0 && df.off$acc_nor[l]<0.99){df.off$acc_nor[l]=NA}
  }
}

#act numbers
df.off=df.off %>% mutate(act_num=NA)
for (k in 1:nrow(df.off)){
  df= df.eve %>% subset(subID==df.off$subID[k] & trName==df.off$trName[k] & act %in% c(0,1))
  ac=df %>% subset(act==1)
  df.off$act_num[k]=nrow(ac)
}

#acylic class vs. aclclic class
df.off$acc_cycClass=0

for (k in 1:nrow(df.off)){
  if (df.off$nodeNum[k]==3){acycBelief=acycBelief3}else{acycBelief=acycBelief4}
  if (df.off$cyclic[k]=="cyclic" && df.off$belief[k]>acycBelief){df.off$acc_cycClass[k]=1}
  if (df.off$cyclic[k]!="cyclic" && df.off$belief[k]<=acycBelief){df.off$acc_cycClass[k]=1}
}

```

```{r demographic}
table(df.dmg$gender)
summarySE(df.dmg,measurevar = "age")
table(df.dmg$delayCond)
```

# ACC
```{r}
#how many times did they confirm their answers
df.jud[time!=0 &online!=-1,.(midjud=.N),by=c("subID","trName","cyclic","nodeNum","delayCond")] %>%
  summarySE(measurevar = 'midjud')
```

```{r}
# final answers vs. initial answers
df.mid=df.jud[time!=0 & online==1,.(midjud=.N,ans_initial=NA,ans_final=NA),by=c("subID","trName")]
for (k in 1:nrow(df.mid)){
  df= df.jud %>% subset(subID==df.mid$subID[k] & trName==df.mid$trName[k] & time!=0 & online!=-1)
  df.mid$ans_initial[k]=df$accLink[1]
  df.mid$ans_final[k]=df$accLink[nrow(df)]
}
nrow(df.mid)/nrow(df.off)
df=df.mid%>%gather(judge,acc,c(ans_final,ans_initial)) %>% mutate(judge=factor(judge,levels = c("ans_initial","ans_final")))
df%>% summarySE(measurevar = 'acc',groupvars = 'judge')
m=lmer(scale(acc)~judge+(1|subID)+(1|trName),df)
m%>% summary()
confint(m) %>% round(2)

df.onl=data.table()
for (k in 1:nrow(df.mid)){
  df= df.jud %>% subset(subID==df.mid$subID[k] & trName==df.mid$trName[k] & time!=0 & online!=-1)
  df.onl=rbind(df.onl,df)
}
df.onl$time_sec=df.onl$time/1000 -1
m=lmer(scale(accLink)~scale(time_sec)+(1|subID)+(1|trName),df.onl) #judOrder is inverse here to make sure the final judgment would always be code as 1
m %>% summary()
confint(m)%>% round(2)
```

```{r}
#structure basic
t.test(summarySE(subset(df.off,delayCond=="reliable"),measurevar = "accLink",groupvars = "subID")$accLink,mu=0.25)
cohen.d(summarySE(subset(df.off,delayCond=="reliable"),measurevar = "accLink",groupvars = "subID")$accLink,f=NA,mu=0.25)
sd(summarySE(subset(df.off,delayCond=="reliable"),measurevar = "accLink",groupvars = "subID")$accLink)

t.test(summarySE(subset(df.off,delayCond=="unreliable"),measurevar = "accLink",groupvars = "subID")$accLink,mu=0.25)
cohen.d(summarySE(subset(df.off,delayCond=="unreliable"),measurevar = "accLink",groupvars = "subID")$accLink,f=NA,mu=0.25)
sd(summarySE(subset(df.off,delayCond=="unreliable"),measurevar = "accLink",groupvars = "subID")$accLink)

lapply(as.list(str_name),function (x){t.test(df.off[trName==x & delayCond=="reliable" ,accLink],mu=0.25)})
lapply(as.list(str_name),function (x){t.test(df.off[trName==x & delayCond=="unreliable" ,accLink],mu=0.25)})
```

```{r}
#description summary
df.off%>% summarySE(measurevar = "accLink",groupvars = "delayCond") %>%  mutate_if(is.numeric, round,2)
df.off%>% summarySE(measurevar = "accLink",groupvars = "cyclic") %>%  mutate_if(is.numeric, round,2)
df.off%>% summarySE(measurevar = "accLink",groupvars = "nodeNum") %>%  mutate_if(is.numeric, round,2)
```

```{r}
#main test
df.off$nodeNum=as.factor(df.off$nodeNum)
m=lmer(scale(accLink)~delayCond+cyclic+nodeNum+(1|subID)+(1|trName),df.off)
m%>% summary() 
confint(m) %>% round(2)
df.mo=df.off %>% mutate(cyclic=factor(cyclic,c("acyclic","unconnected","cyclic")))
m=lmer(scale(accLink)~delayCond+cyclic+nodeNum+(1|subID)+(1|trName),df.mo)
m%>% summary() 
confint(m) %>% round(2)

m=lmer(scale(accLink)~delayCond*cyclic*nodeNum+(1|subID)+(1|trName),df.off)
m%>% summary()
```

```{r}
summarySE(df.off,measurevar = "acc_cycClass",groupvars = c("cyclic"),na.rm = T)
x=summarySE(df.off,measurevar = "acc_cycClass",groupvars = c("cyclic","subID"),na.rm = T)
t.test(acc_cycClass~cyclic,subset(x,cyclic!="unconnected"),paired=T)
```


# IO accuracy
```{r}
df.off%>% summarySE(measurevar = "acc_nor",groupvars = "cyclic",na.rm = T) %>%  mutate_if(is.numeric, round,2)
df.off%>% summarySE(measurevar = "acc_nor",groupvars = "nodeNum",na.rm = T) %>%  mutate_if(is.numeric, round,2)

```

```{r}
m=lmer(scale(acc_nor)~delayCond+cyclic+nodeNum+(1|subID)+(1|trName),df.off)
m%>% summary()
confint(m)%>% round(2)

df.mo=df.off %>% mutate(cyclic=factor(cyclic,c("acyclic","unconnected","cyclic")))
m=lmer(scale(acc_nor)~delayCond+cyclic+nodeNum+(1|subID)+(1|trName),df.mo)
m%>% summary()
confint(m)%>% round(2)
```

```{r}
m=lmer(scale(accLink)~scale(acc_nor)+(1|subID)+(1|trName),df.off)
m%>% summary()
confint(m)%>% round(2)
```


```{r}
df.off %>%
  reshape2::melt(id.vars=setdiff(colnames(df.off),c("accLink","acc_nor")),value.name = "Accuracy", variable.name="Learner")%>%
  summarySE(measurevar = "Accuracy",groupvars = c('cyclic','delayCond',"Learner"),na.rm=T)%>%
  mutate(Learner=factor(Learner,levels = c("accLink","acc_nor"),
                        labels = c("Participants","Ideal Observer")),
         cyclic=factor(cyclic,levels = c("unconnected",'acyclic',"cyclic"),labels = c("Unlinked","Acyclic","Cyclic")),
         delayCond=factor(delayCond,levels = c('reliable',"unreliable"),labels = c("Reliable","Unreliable")),
         gr=paste(Learner,delayCond))%>%
  ggplot(aes(x=cyclic,y=Accuracy,color=Learner,group=gr,linetype=delayCond))+
  geom_point()+
  geom_line()+
  geom_errorbar(aes(ymin=Accuracy-ci, ymax=Accuracy+ci),
                width=.1)+
  scale_colour_manual(values = c("black", "#FEAE00")) +
  scale_linetype_manual(name="Delay", values=c("Reliable"="solid","Unreliable"="dashed")) +
  xlab("Cyclicity")+
  ylab("Accuracy")+
  theme_bw()+
  scale_y_continuous(limits = c(0.4,1.0))+
  theme(text = element_text(size=15),
        axis.text=element_text(colour="black"),
        axis.line = element_line(color = 'black'),
        panel.border = element_blank(),
        panel.grid = element_blank(),
        strip.background =element_rect(fill="white",color="white"),legend.position = "none",
        panel.background = element_rect(fill = "transparent",colour = NA),
        plot.background = element_rect(fill = "transparent",colour = NA))

#ggsave(file="exp2_acc_cyc.pdf",width = 5,height = 3.5, bg="transparent")

```

```{r}
df.off %>%
  reshape2::melt(id.vars=setdiff(colnames(df.off),c("accLink","acc_nor")),value.name = "Accuracy", variable.name="Learner")%>%
  summarySE(measurevar = "Accuracy",groupvars = c('nodeNum','delayCond',"Learner"),na.rm=T)%>%
  mutate(Learner=factor(Learner,levels = c("accLink","acc_nor"),
                        labels = c("Participants","Ideal Observer")),
         nodeNum=factor(nodeNum,levels = c('3',"4"),labels = c("Three-node","Four-node")),
         delayCond=factor(delayCond,levels = c('reliable',"unreliable"),labels = c("Reliable","Unreliable")),
         gr=paste(Learner,delayCond))%>%
  ggplot(aes(x=nodeNum,y=Accuracy,color=Learner,group=gr,linetype=delayCond))+
  geom_point()+
  geom_line()+
  geom_errorbar(aes(ymin=Accuracy-ci, ymax=Accuracy+ci),
                width=.1)+
  scale_colour_manual(values = c("black", "#FEAE00")) +
  scale_linetype_manual(name="Delay", values=c("Reliable"="solid","Unreliable"="dashed")) +
  xlab("Structure Nodes")+
  ylab("Accuracy")+
  theme_bw()+
  scale_y_continuous(limits = c(0.4,1.0))+
  theme(text = element_text(size=15),
        axis.text=element_text(colour="black"),
        axis.line = element_line(color = 'black'),
        panel.border = element_blank(),
        panel.grid = element_blank(),
        strip.background =element_rect(fill="white",color="white"),legend.position = "none",
        panel.background = element_rect(fill = "transparent",colour = NA),
        plot.background = element_rect(fill = "transparent",colour = NA))
# ggsave(file="exp2_acc_nod.pdf",width = 4,height = 3.5, bg="transparent")
```

# Total events
```{r}
# df.off%>% summarySE(measurevar = "eve_num",groupvars = "delayCond",na.rm = T) %>%  mutate_if(is.numeric, round,2)
df.off%>% summarySE(measurevar = "eve_num",groupvars = "cyclic",na.rm = T) %>%  mutate_if(is.numeric, round,2)
# df.off%>% summarySE(measurevar = "eve_num",groupvars = "nodeNum",na.rm = T) %>%  mutate_if(is.numeric, round,2)

```

```{r}
m=lmer(scale(eve_num)~delayCond+cyclic+nodeNum+(1|subID)+(1|trName),df.off)
m%>% summary()
confint(m) %>% round(2)
df.mo=df.off %>% mutate(cyclic=factor(cyclic,c("acyclic","unconnected","cyclic")))
m=lmer(scale(eve_num)~delayCond+cyclic+nodeNum+(1|subID)+(1|trName),df.mo)
m%>% summary()
confint(m) %>% round(2)

m=lmer(scale(eve_num)~delayCond*cyclic*nodeNum+(1|subID)+(1|trName),df.off)
m%>% summary()
df.mo=df.off %>% mutate(cyclic=factor(cyclic,c("acyclic","unconnected","cyclic")))
m=lmer(scale(eve_num)~delayCond*cyclic*nodeNum+(1|subID)+(1|trName),df.mo)
m%>% summary()
```

```{r}
m=lmer(scale(accLink)~scale(eve_num)+(1|subID)+(1|trName),df.off)
m%>% summary()
confint(m)%>% round(2)
```

```{r}
#color for global event plot
cols<-colorRampPalette(c("#226103","#F7F7F7","#a80d00"), space="rgb")(12)
df.off %>%
  summarySE(measurevar = "eve_num",groupvars = c('cyclic','delayCond'),na.rm=T)%>%
  mutate(color=cols[ceiling((eve_num-5)/3)])

df.off %>%
  summarySE(measurevar = "eve_num",groupvars = c('nodeNum','delayCond'),na.rm=T)%>%
  mutate(color=cols[ceiling((eve_num-5)/3)])
```

# Event density
```{r}
df.off%>% summarySE(measurevar = "eve_den",groupvars = "cyclic",na.rm = T) %>%  mutate_if(is.numeric, round,2)
```

```{r}
m=lmer(scale(eve_den)~delayCond+cyclic+nodeNum+(1|subID)+(1|trName),df.off)
m%>% summary()
confint(m) %>% round(2)
m=lmer(scale(eve_den)~delayCond*cyclic*nodeNum+(1|subID)+(1|trName),df.off)
m%>% summary()

df.mo=df.off %>% mutate(cyclic=factor(cyclic,c("acyclic","unconnected","cyclic")))
m=lmer(scale(eve_den)~delayCond+cyclic+nodeNum+(1|subID)+(1|trName),df.mo)
m%>% summary()
confint(m) %>% round(2)
m=lmer(scale(eve_den)~delayCond*cyclic*nodeNum+(1|subID)+(1|trName),df.mo)
m%>% summary()
confint(m) %>% round(2)

summarySE(df.mo, measurevar = "eve_den",groupvars = c("cyclic","delayCond"))
```

```{r}
m=lmer(scale(accLink)~scale(eve_den)+(1|subID)+(1|trName),df.off)
m%>% summary()
confint(m)%>% round(2)
```

```{r}
#appendix:choices for different window size
df.eve=df.eve %>% mutate(wd=ceiling(time/1000))
df.roll=df.off
for (k in 1:nrow(df.off)){
  df= df.eve %>% subset(subID==df.off$subID[k] & trName==df.off$trName[k] & act %in% c(0,1))
  ev=matrix(NA,ncol=45,nrow=7)
  for (w in 1:45){
    for (e in 1:nrow(ev)){
      ev[e,w]=nrow(subset(df,wd<=w & wd>=w-e+1))
    }
  }
  for (e in 1:nrow(ev)){
    df.roll[k,paste("eve_den",e,sep="")]=max(ev[e,])
  }
}

df.roll=df.roll %>% mutate(eve_den=eve_den1)
m=lmer(scale(accLink)~scale(eve_den)+(1|subID)+(1|trName),df.roll)
m%>% summary()
confint(m)%>% round(2)
```

# Predicting ACC
```{r}
lmer(scale(acc_nor)~scale(act_num)+(1|subID)+(1|trName),df.off)%>%summary()
lmer(scale(acc_nor)~scale(act_num)+(1|subID)+(1|trName),df.off)%>%confint()%>% round(2)

lmer(scale(eve_num)~scale(act_num)+(1|subID)+(1|trName),df.off)%>%summary()
lmer(scale(eve_num)~scale(act_num)+(1|subID)+(1|trName),df.off)%>%confint()%>% round(2)

lmer(scale(eve_den)~scale(act_num)+(1|subID)+(1|trName),df.off)%>%summary()
lmer(scale(eve_den)~scale(act_num)+(1|subID)+(1|trName),df.off)%>%confint()%>% round(2)


lmer(scale(acc_nor)~scale(blc_yn)+(1|subID)+(1|trName),df.off)%>%summary()
lmer(scale(acc_nor)~scale(blc_yn)+(1|subID)+(1|trName),df.off)%>%confint()%>% round(2)

lmer(scale(eve_num)~scale(blc_yn)+(1|subID)+(1|trName),df.off)%>%summary()
lmer(scale(eve_num)~scale(blc_yn)+(1|subID)+(1|trName),df.off)%>%confint()%>% round(2)

lmer(scale(eve_den)~scale(blc_yn)+(1|subID)+(1|trName),df.off)%>%summary()
lmer(scale(eve_den)~scale(blc_yn)+(1|subID)+(1|trName),df.off)%>%confint()%>% round(2)
```

```{r}
m=lmer(scale(accLink)~scale(acc_nor)+scale(act_num)+scale(blc_yn)+scale(eve_num)+scale(eve_den)+(1|subID)+(1|trName),df.off)
m%>%summary()
confint(m)%>% round(2)
```

# When to intervene
```{r}
df.off%>% summarySE(measurevar = "act_num",groupvars = "nodeNum",na.rm = T) %>%  mutate_if(is.numeric, round,2)
df.off%>% summarySE(measurevar = "act_num",groupvars = "delayCond",na.rm = T) %>%  mutate_if(is.numeric, round,2)
df.off%>% summarySE(measurevar = "act_num",groupvars = "cyclic",na.rm = T) %>%  mutate_if(is.numeric, round,2)
```

```{r}
m=lmer(scale(act_num)~delayCond+cyclic+nodeNum+(1|subID)+(1|trName),df.off)
m%>% summary()
confint(m) %>% round(2)
m=lmer(scale(act_num)~delayCond*cyclic*nodeNum+(1|subID)+(1|trName),df.off)
m%>% summary()
df.mo=df.off %>% mutate(cyclic=factor(cyclic,c("acyclic","unconnected","cyclic")))
m=lmer(scale(act_num)~delayCond+cyclic+nodeNum+(1|subID)+(1|trName),df.mo)
m%>% summary()
confint(m) %>% round(2)
m=lmer(scale(act_num)~delayCond*cyclic*nodeNum+(1|subID)+(1|trName),df.mo)
m%>% summary()
```

```{r}
#interval
df.act=data.table()
for (i in unique(df.eve$subID)){
  for (j in unique(df.eve$trName)){
    sub=df.eve[subID==i & trName==j]
    sub$eve_gap=c(NA,diff(sub$time))
    act=sub[act==1]
    act$ActOrder=c(1:nrow(act))
    act$gap=c(NA,diff(act$time))
    act$cyclic=as.character(unique(df.off[subID==i&trName==j,cyclic]))
    df.act=rbind(df.act,act)
  }
}
#calibration for time
df.act$judtime=df.act$eve_judtime=0
df.jud$online=as.numeric(df.jud$online)
for (k in 1:nrow(df.act)){
  if (is.na(df.act$gap[k])){next}
  df=df.jud %>% subset(subID==df.act$subID[k] &
                         trName==df.act$trName[k] & 
                         time<df.act$time[k] & 
                         time>df.act$time[k-1])
  if (nrow(df)==0){next}
  df$mid=c(-2,diff(df$online))
  df=df%>% subset(mid!=0)
  if (nrow(df)==0){next}
  df$subs=c(0,diff(df$time))
  df=df%>% subset(mid==2)
  if (nrow(df)==0){next}
  df.act$judtime[k]=sum(df$subs)
  
  df=df%>% subset(time>df.act$time[k]-df.act$eve_gap[k])
  if(nrow(df)==0){next}
  df$eve_time=df$time-df$subs
  df$eve_time=pmax(df.act$time[k]-df.act$eve_gap[k],df$eve_time)
  df$subs=df$time-df$eve_time
  df.act$eve_judtime[k]=sum(df$subs)
}

df.act=df.act%>%mutate(delayCond=as.factor(delayCond),
                       cyclic=as.factor(cyclic),
                       nodeNum=as.factor(nodeNum),
                       gap_new=gap-judtime,
                       eve_gap_new=eve_gap-eve_judtime)

df.act.agg=df.act[,.(gap_new=mean(gap_new,na.rm=T),gap=mean(gap,na.rm=T)), by=c("subID","trName","delayCond","cyclic",'nodeNum')]
```

```{r}
summarySE(df.act.agg,measurevar = "gap",groupvars = "cyclic",na.rm = T)
```

```{r}
summarySE(df.act.agg,measurevar = "gap_new",groupvars = "cyclic",na.rm = T)
```

```{r}
m=lmer(scale(gap)~delayCond+cyclic+nodeNum+(1|subID)+(1|trName),df.act.agg)
m%>% summary()
confint(m) %>% round(2)
m=lmer(scale(gap)~delayCond*cyclic*nodeNum+(1|subID)+(1|trName),df.act.agg)
m%>% summary()

df.mo=df.act.agg %>% mutate(cyclic=factor(cyclic,c("acyclic","unconnected","cyclic")))
m=lmer(scale(gap)~delayCond+cyclic+nodeNum+(1|subID)+(1|trName),df.mo)
m%>% summary()
confint(m) %>% round(2)
m=lmer(scale(gap)~delayCond*cyclic*nodeNum+(1|subID)+(1|trName),df.mo)
m%>% summary()
```


```{r}
m=lmer(scale(gap_new)~delayCond+cyclic+nodeNum+(1|subID)+(1|trName),df.act.agg)
m%>% summary()
confint(m) %>% round(2)
m=lmer(scale(gap_new)~delayCond*cyclic*nodeNum+(1|subID)+(1|trName),df.act.agg)
m%>% summary()

df.mo=df.act.agg %>% mutate(cyclic=factor(cyclic,c("acyclic","unconnected","cyclic")))
m=lmer(scale(gap_new)~delayCond+cyclic+nodeNum+(1|subID)+(1|trName),df.mo)
m%>% summary()
confint(m) %>% round(2)
m=lmer(scale(gap_new)~delayCond*cyclic*nodeNum+(1|subID)+(1|trName),df.mo)
m%>% summary()
```

```{r}
df.act.agg.fig=df.act.agg%>%  mutate(interval=gap_new/1000) %>%
  mutate(cyclic=factor(cyclic,levels = c("unconnected","acyclic","cyclic"),labels = c("Unlinked","Acyclic","Cyclic"))
  )
```

```{r}
df.act.agg.fig%>%#(trName %in% v.sti.exp1|cyclic=="unconnected") &
  summarySE(measurevar = "interval",groupvars = c('cyclic'),na.rm=T)%>%
  ggplot(aes(x=cyclic,y=interval))+
  geom_bar(stat = "identity",color="black",fill="white")+
  geom_errorbar(aes(ymin=interval-ci, ymax=interval+ci),
                width=.3)+
  geom_jitter(data=df.act.agg.fig,aes(x=cyclic,y=interval),alpha=0.05)+
  xlab("Cyclicity")+
  ylab("Interval (s)")+
  scale_y_continuous(limits = c(0,36))+
  theme_bw()+
  theme(text = element_text(size=16),
        axis.line = element_line(color = 'black'),
        panel.border = element_blank(),
        axis.text=element_text(colour="black"),
        plot.background = element_blank(),
        strip.background =element_rect(fill="white",color = "white"),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        legend.position = 'none')
# ggsave(file="exp2_timing.pdf",width = 5,height = 5.5)
```


```{r}
#one-intervention local events
load("df.locevesim.Rda")
df1=df.locevesim %>% 
  summarySE(measurevar = "eve_den",groupvars =c("trName"),na.rm = T)%>% 
  mutate(eve_ci=ci)
df2=df.act.agg %>% 
  mutate(gap_new=gap_new/1000) %>% 
  summarySE(measurevar = "gap_new",groupvars =c("trName","cyclic",'nodeNum'),na.rm = T) %>% 
  mutate(gap_ci=ci)
df3=df.act.agg %>% 
  mutate(gap=gap/1000) %>% 
  summarySE(measurevar = "gap",groupvars =c("trName","cyclic"),na.rm = T) %>% 
  mutate(gap_ori_ci=ci)

df.label=data.frame(trName=str_name,
                    trLabel=c("A1","A2","A3",
                              "A4","A5","A6",
                              "U1","A7","U2",
                              "A8","C2","C1",
                              "C3","C5","C4",
                              "C6","C7","C8"))
df.act.fig=merge(df1,df2,by=c("trName")) %>% merge(df.label,by=c("trName")) %>% merge(df3,by=c("trName"))
```


```{r}
df.act.fig%>%
  mutate(nodeNum=factor(nodeNum,levels = c("3",'4'),labels = c("Three-node","Four-node")))%>%
  ggplot(aes(x=eve_den,y=gap,label=trLabel,color=nodeNum))+
  # facet_wrap(~nodeNum)+
  geom_point()+
  geom_errorbar(aes(ymin = gap-gap_ori_ci,ymax = gap+gap_ori_ci),width=0) + 
  geom_errorbarh(aes(xmin = eve_den-eve_ci,xmax = eve_den+eve_ci))+
  geom_text_repel(alpha=0.3,color="black")+
  xlab("Peak Event Density by One Random Intervention")+
  ylab("Interval (s)")+
  theme_bw()+
  scale_x_continuous(limits = c(0.95,4.15))+
  scale_y_continuous(limits = c(2+2,10+2))+
  # scale_linetype_manual(name="Delay", values=c("Reliable"="solid","Unreliable"="dashed")) +
  scale_colour_manual(name="Structure Nodes",values = c("black", "#FEAE00")) +
  theme(text = element_text(size=13),
        axis.text=element_text(colour="black"),
        axis.line = element_line(color = 'black'),
        plot.background = element_blank(),
        panel.border = element_blank(),
        strip.background =element_rect(fill="white",color = "white"),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        legend.position = 'none')
# ggsave(file="exp2_locevesim.pdf",width = 9,height = 2.5)
```

#where to intervene
```{r}
df.where=df.eve %>% subset(act==1) %>% 
  mutate(uni_trial=paste(subID,trName,sep="_"),actNum=NA,newNode=NA)
for (k in unique(df.where$uni_trial)){
  a_idx=which(df.where$uni_trial==k)
  df.where$actNum[a_idx]=seq(1:length(a_idx))
  df.where$newNode[a_idx[1]]=T
  if (length(a_idx)==1){next}
  for (i in 2:length(a_idx)){
    df.where$newNode[a_idx[i]]=!(df.where$obj[a_idx[i]] %in% df.where$obj[a_idx[1:(i-1)]])
  }
}
```

```{r}
load("mdall_exp2.Rda")
tmp1=mdall%>%
  subset(subAct%in%c("A","B","C","D") & choice %in% c("A","B","C","D"))%>%
  group_by(uni_label,subID,trName,wd,nodeNum)%>%
  dplyr::summarise(eig_sum=sum(eig_gr))
IOchoice=mdall%>%
  subset(subAct%in%c("A","B","C","D") & choice %in% c("A","B","C","D"))%>%
  group_by(uni_label,subID,trName,nodeNum,wd,choice,eig_gr)%>%
  dplyr::summarise(eig=mean(eig_gr))%>%
  merge(tmp1,by=c("uni_label","subID","trName","wd","nodeNum"))%>%
  mutate(prob=eig/eig_sum,uni_trial=paste(subID,trName,sep="_"))

df.where$newIOprob=NA
for (k in 1:nrow(df.where)){
  old=df.where %>% subset(uni_trial==df.where$uni_trial[k] & wd< df.where$wd[k])
  if (nrow(old)==0){
    df.where$newIOprob[k]=1
  }else{
    tmp=IOchoice %>% subset(uni_trial==df.where$uni_trial[k] & wd== df.where$wd[k])
    if (length(which.max(tmp$prob))==0){next}
    df.where$newIOprob[k]=!(sample(tmp$choice[which.max(tmp$prob)],1)%in%old$obj)
  }
}

summarySE(df.where,measurevar = "newIOprob",groupvars = c("nodeNum","actNum"),na.rm=T)
```


```{r}
df.where %>% 
  summarySE(measurevar = "newNode",groupvars = c("subID","nodeNum","actNum"))%>%
  summarySE(measurevar = "newNode",groupvars = c("nodeNum","actNum"))%>%
  mutate(rdline=c(c(1,2/3,4/9,8/27,16/81,32/243),c(1,3/4,9/16,27/64,81/256,243/1024)),
         ioline=c(c(1,0.87,0.66,0.18,0.09,0.05),c(1,0.92,0.77,0.59,0.21,0.11))
         )%>%
  ggplot(aes(x=actNum,y=newNode))+
  facet_wrap(~nodeNum,labeller = as_labeller(c("3"="Three-node Structure","4"="Four-node Structure")))+
  geom_bar(stat="identity",color="black",fill="white",position=position_dodge(.9))+#"#D5D5D5"
  geom_errorbar(aes(ymin = newNode-ci,ymax=newNode+ci),width=0,size=0.8,position=position_dodge(.9))+
    geom_errorbar(aes(ymin = rdline,ymax =rdline),width=1,size=0.8,position=position_dodge(.9),color=alpha("#FEAE00",0.6))+
  geom_errorbar(aes(ymin = ioline,ymax =ioline),width=1,size=0.8,position=position_dodge(.9),color=alpha("#44792A",0.6))+
  theme_bw()+
  xlab(expression(paste("The ", X^th," Activating Intervention")))+
  ylab("Intervening on a New Node")+
  scale_x_continuous(breaks = c(1:6))+
  geom_vline(data=filter(df.where, nodeNum==3), aes(xintercept=3.5), colour="gray",linetype="dashed") + 
  geom_vline(data=filter(df.where, nodeNum==4), aes(xintercept=4.5), colour="gray",linetype="dashed") + 
  theme(text = element_text(size=12),
        axis.text=element_text(colour="black"),
        # axis.line = element_line(color = 'black'),
        # panel.border = element_blank(),
        strip.text.x = element_text(size = 12),
        panel.grid = element_blank(),
        strip.background =element_rect(fill="white",color="white"),legend.position = "none",
        panel.background = element_rect(fill = "transparent",colour = NA),
        plot.background = element_rect(fill = "transparent",colour = NA))
# ggsave(file="exp2_new.pdf",width = 7,height = 3.5)
```


```{r}
tmp=df.where %>% subset(nodeNum==3 & actNum==2)%>%
  summarySE(measurevar = "newNode",groupvars = c("actNum","subID"))

t.test(tmp$newNode,mu=2/3)

tmp=df.where %>% subset(nodeNum==3 & actNum==3)%>%
  summarySE(measurevar = "newNode",groupvars = c("actNum","subID"))

t.test(tmp$newNode,mu=4/9)


tmp=df.where %>% subset(nodeNum==3 & actNum==4)%>%
  summarySE(measurevar = "newNode",groupvars = c("actNum","subID"))

t.test(tmp$newNode,mu=8/27)

tmp=df.where %>% subset(nodeNum==3 & actNum==5)%>%
  summarySE(measurevar = "newNode",groupvars = c("actNum","subID"))

t.test(tmp$newNode,mu=16/81)


tmp=df.where %>% subset(nodeNum==3 & actNum==6)%>%
  summarySE(measurevar = "newNode",groupvars = c("actNum","subID"))

t.test(tmp$newNode,mu=32/243)
```

```{r}
tmp=df.where %>% subset(nodeNum==4 & actNum==2)%>%
  summarySE(measurevar = "newNode",groupvars = c("actNum","subID"))

t.test(tmp$newNode,mu=3/4)

tmp=df.where %>% subset(nodeNum==4 & actNum==3)%>%
  summarySE(measurevar = "newNode",groupvars = c("actNum","subID"))

t.test(tmp$newNode,mu=9/16)


tmp=df.where %>% subset(nodeNum==4 & actNum==4)%>%
  summarySE(measurevar = "newNode",groupvars = c("actNum","subID"))

t.test(tmp$newNode,mu=27/64)

tmp=df.where %>% subset(nodeNum==4 & actNum==5)%>%
  summarySE(measurevar = "newNode",groupvars = c("actNum","subID"))

t.test(tmp$newNode,mu=81/256)


tmp=df.where %>% subset(nodeNum==4 & actNum==6)%>%
  summarySE(measurevar = "newNode",groupvars = c("actNum","subID"))

t.test(tmp$newNode,mu=243/1024)
```


```{r}
df.eve=df.eve %>% mutate(uni_trial=paste(subID,trName,sep="_"))
df.comf=df.eve %>% subset(act==1) %>% mutate(eve_chosen=NA,eve_unchosen=NA)
for (k in 1:nrow(df.comf)){
  df=df.eve %>% subset(uni_trial==df.comf$uni_trial[k]&act!=-1) %>% 
    subset(time<df.comf$time[k])
  if (nrow(df)==0){next}
  act=df%>% subset(act==1)
  a=which(act$obj==df.comf$obj[k])
  if (length(a)==0){next}
  if (length(a)==nrow(act)){next}
  
  for (i in 1:(nrow(act)-1)){
      b=act$time[i]
      e=act$time[i+1]
      act$est_eve[i]= nrow(subset(df,time>b &time<e))
  }
   b=act$time[nrow(act)]
   act$est_eve[nrow(act)]= nrow(subset(df,time>b))
  
   tmp=act%>% group_by(obj) %>%dplyr::summarise(m=mean(est_eve))
   
   df.comf$eve_chosen[k]= mean(tmp$m[tmp$obj==df.comf$obj[k]])
   df.comf$eve_unchosen[k]= mean(tmp$m[tmp$obj!=df.comf$obj[k]])
}

df.comf.test=df.comf %>% reshape2::melt(id.vars=setdiff(colnames(df.comf),c("eve_unchosen","eve_chosen")),value.name = "eve_expected", variable.name="choice")
```

```{r}
lmer(scale(eve_expected)~choice+(1|subID)+(1|trName),subset(df.comf.test,cyclic!="unconnected"))%>%summary()
lmer(scale(eve_expected)~choice+(1|subID)+(1|trName),subset(df.comf.test,cyclic!="unconnected"))%>%confint()
summarySE(subset(df.comf.test,cyclic!="unconnected"),measurevar ="eve_expected",groupvars = "choice",na.rm = T)

lmer(scale(eve_expected)~choice+(1|subID)+(1|trName),subset(df.comf.test,cyclic=="acyclic"))%>%summary()
lmer(scale(eve_expected)~choice+(1|subID)+(1|trName),subset(df.comf.test,cyclic=="acyclic"))%>%confint()
summarySE(df.comf.test,measurevar ="eve_expected",groupvars = c("cyclic","choice"),na.rm = T)

lmer(scale(eve_expected)~choice+(1|subID)+(1|trName),subset(df.comf.test,cyclic=="cyclic"))%>%summary()
lmer(scale(eve_expected)~choice+(1|subID)+(1|trName),subset(df.comf.test,cyclic=="cyclic"))%>%confint()
```


# Blocking
```{r}
df.off=df.off %>% mutate(blc_num=0,blc_all=0,blc_reset=0,blc_ctrl=0,blc_other=0)
df.blc=data.table()
for (k in 1:nrow(df.off)){
  sub=df.eve %>% subset(subID==df.off$subID[k] & trName==df.off$trName[k])
  blc=sub %>% subset(blc==-1)
  ac=sub %>% subset(act==1)
  
  # df.off$blc_all[k]=nrow(blc)
  #
  df.off$blc_num[k]=nrow(blc)
  
  if (nrow(ac)==6){
    ac_final=max(ac$time)
  }else{
    ac_final=45*1000
  }
  
  if (nrow(blc)==0){next}
  blc$code=NA
  for(j in 1:nrow(blc)){
    curobj=as.character(blc[j,"obj"])
    unblc=sub %>% subset(obj==curobj &blc==1)
    reset=pmax(0,unblc[,time])-blc$time[j]
    ctrl=pmax(0,ac$time)-blc$time[j]
    reset[which(reset<0)]=0
    ctrl[which(ctrl<0)]=0
    if (blc$time[j]>ac_final || max(reset,0)==max(ctrl,0)){
      blc$code[j]="other"
      df.off$blc_other[k]=df.off$blc_other[k]+1
    }else if (max(ctrl,0)==0){
      blc$code[j]="reset"
      df.off$blc_reset[k]=df.off$blc_reset[k]+1
    }else if (max(reset,0)==0){
      blc$code[j]="ctrl"
      df.off$blc_ctrl[k]=df.off$blc_ctrl[k]+1
    }else{
      if (max(ctrl)<max(reset)){
        blc$code[j]="ctrl"
        df.off$blc_ctrl[k]=df.off$blc_ctrl[k]+1
      }else{
        blc$code[j]="reset"
        df.off$blc_reset[k]=df.off$blc_reset[k]+1
      }
    }
  }
  df.blc=rbind(df.blc,blc)
}

df.off=df.off %>% mutate(blc_yn_ctrl=as.numeric(blc_ctrl>0),
                         blc_yn_reset=as.numeric(blc_reset>0),
                         blc_yn_other=as.numeric(blc_other>0),
                         blc_yn=as.numeric(blc_yn_ctrl|blc_yn_reset|blc_yn_other))

length(unique(df.off[blc_yn!=0,subID]))/nrow(df.dmg) #how many people use blocking
```

```{r}
sum(df.off$blc_num)
mean(df.off$blc_yn)
summarySE(df.off,measurevar = "blc_num")

summarySE(df.off,measurevar = "blc_yn",groupvars = "delayCond")
summarySE(df.off,measurevar = "blc_yn",groupvars = "nodeNum")
summarySE(df.off,measurevar = "blc_yn",groupvars = "cyclic")
```

```{r}
m=glmer(blc_yn~delayCond+cyclic+nodeNum+(1|subID)+(1|trName),df.off,family = "binomial",
        glmerControl(optimizer="bobyqa", optCtrl = list(maxfun = 50000)))
m%>% summary()
m=glmer(blc_yn~delayCond*cyclic*nodeNum+(1|subID)+(1|trName),df.off,family = "binomial",
        glmerControl(optimizer="bobyqa", optCtrl = list(maxfun = 50000)))
m%>% summary()
df.mo=df.off %>% mutate(cyclic=factor(cyclic,c("acyclic","unconnected","cyclic")))
m=glmer(blc_yn~delayCond+cyclic+nodeNum+(1|subID)+(1|trName),df.mo,family = "binomial",
        glmerControl(optimizer="bobyqa", optCtrl = list(maxfun = 50000)))
m%>% summary()
confint.merMod(m,method = "Wald")
m=glmer(blc_yn~delayCond*cyclic*nodeNum+(1|subID)+(1|trName),df.mo,family = "binomial",
        glmerControl(optimizer="bobyqa", optCtrl = list(maxfun = 50000)))
m%>% summary()
```

```{r}
summarySE(df.off,measurevar = "blc_yn_reset",groupvars = "cyclic")
summarySE(df.off,measurevar = "blc_yn_reset",groupvars = "nodeNum")
summarySE(df.off,measurevar = "blc_yn_other",groupvars = "delayCond")
summarySE(df.off,measurevar = "blc_yn_other",groupvars = "nodeNum")
summarySE(df.off,measurevar = "blc_yn_other",groupvars = "cyclic")
```

```{r}
m=glmer(blc_yn_reset~delayCond+cyclic+nodeNum+(1|subID)+(1|trName),df.off,family = "binomial",
        glmerControl(optimizer="bobyqa", optCtrl = list(maxfun = 50000)))
m%>% summary()
confint.merMod(m,method = "Wald")
m=glmer(blc_yn_reset~delayCond*cyclic*nodeNum+(1|subID)+(1|trName),df.off,family = "binomial",
        glmerControl(optimizer="bobyqa", optCtrl = list(maxfun = 50000)))
m%>% summary()
df.mo=df.off %>% mutate(cyclic=factor(cyclic,c("acyclic","unconnected","cyclic")))
m=glmer(blc_yn_reset~delayCond+cyclic+nodeNum+(1|subID)+(1|trName),df.mo,family = "binomial",
        glmerControl(optimizer="bobyqa", optCtrl = list(maxfun = 50000)))
m%>% summary()
confint.merMod(m,method = "Wald")
m=glmer(blc_yn_reset~delayCond*cyclic*nodeNum+(1|subID)+(1|trName),df.mo,family = "binomial",
        glmerControl(optimizer="bobyqa", optCtrl = list(maxfun = 50000)))
m%>% summary()
```

```{r}
summarySE(df.off,measurevar = "blc_yn_ctrl",groupvars = "cyclic")
m=glmer(blc_yn_ctrl~delayCond+cyclic+nodeNum+(1|subID)+(1|trName),df.off,family = "binomial",
        glmerControl(optimizer="bobyqa", optCtrl = list(maxfun = 50000)))
m%>% summary()
m=glmer(blc_yn_ctrl~delayCond*cyclic*nodeNum+(1|subID)+(1|trName),df.off,family = "binomial",
        glmerControl(optimizer="bobyqa", optCtrl = list(maxfun = 50000)))
m%>% summary()
df.mo=df.off %>% mutate(cyclic=factor(cyclic,c("acyclic","unconnected","cyclic")))
m=glmer(blc_yn_ctrl~delayCond+cyclic+nodeNum+(1|subID)+(1|trName),df.mo,family = "binomial",
        glmerControl(optimizer="bobyqa", optCtrl = list(maxfun = 50000)))
m%>% summary()
confint.merMod(m,method = "Wald")
m=glmer(blc_yn_ctrl~delayCond*cyclic*nodeNum+(1|subID)+(1|trName),df.mo,family = "binomial",
        glmerControl(optimizer="bobyqa", optCtrl = list(maxfun = 50000)))
m%>% summary()
```

```{r}
summarySE(df.off,measurevar = "blc_yn_other",groupvars = "cyclic")
m=glmer(blc_yn_other~delayCond+cyclic+nodeNum+(1|subID)+(1|trName),df.off,family = "binomial",
        glmerControl(optimizer="bobyqa", optCtrl = list(maxfun = 50000)))
m%>% summary()
m=glmer(blc_yn_other~delayCond*cyclic*nodeNum+(1|subID)+(1|trName),df.off,family = "binomial",
        glmerControl(optimizer="bobyqa", optCtrl = list(maxfun = 50000)))
m%>% summary()
df.mo=df.off %>% mutate(cyclic=factor(cyclic,c("acyclic","unconnected","cyclic")))
m=glmer(blc_yn_other~delayCond+cyclic+nodeNum+(1|subID)+(1|trName),df.mo,family = "binomial",
        glmerControl(optimizer="bobyqa", optCtrl = list(maxfun = 50000)))
m%>% summary()
confint.merMod(m,method = "Wald")
m=glmer(blc_yn_other~delayCond*cyclic*nodeNum+(1|subID)+(1|trName),df.mo,family = "binomial",
        glmerControl(optimizer="bobyqa", optCtrl = list(maxfun = 50000)))
m%>% summary()
```

```{r}
df.blc.type=df.off %>%
  melt(id.vars=setdiff(colnames(df.off),c("blc_yn","blc_yn_ctrl","blc_yn_reset","blc_yn_other")),variable.name="blc_type",value.name = "blc") %>%
  mutate(blc_raw=blc,
         blc=c("Blocks=0","Blocks>0")[blc+1],
         value=1,
         blc_type=factor(blc_type,levels = c("blc_yn","blc_yn_reset","blc_yn_ctrl","blc_yn_other"),labels = c("Overall","Resetting","Controlling","Other")),
         cyclic=factor(cyclic,levels = c("unconnected","acyclic","cyclic"),labels = c("Unlinked","Acyclic","Cyclic"))
         )
df.blc.ci=df.blc.type %>% mutate(y=blc_raw) %>% 
  summarySE(measurevar = "y",groupvars = c("blc_type","cyclic"))

df.blc.y=df.blc.type %>% summarySE(measurevar = "blc_raw",groupvars = c("blc_type","cyclic","blc")) %>% mutate(ci=NULL)
df.blc.y$y=NA
for (k in 1:nrow(df.blc.y)){
  t=df.blc.y$blc_type[k]  %>% as.character()
  c=df.blc.y$cyclic[k] %>% as.character()
  df.blc.y$y[k]=df.blc.y$N[k]/nrow(subset(df.blc.type,blc_type==t&cyclic==c))
  if (df.blc.y$blc[k]=="Blocks>0"){df.blc.y$ci[k]= df.blc.ci$ci[df.blc.ci$cyclic==c & df.blc.ci$blc_type==t]}
}
```


```{r}
df.blc.y%>%ggplot(aes(x=cyclic,y=y)) + 
  facet_wrap(~blc_type,ncol=4)+
  geom_bar(stat="identity", aes(fill=blc) )+
  xlab("Cyclicity")+
  ylab("Percentage")+
  scale_fill_grey(name="Blocking Times",start = .9, end = .5)+
  geom_errorbar(aes(ymin = y-ci,ymax = y+ci),width=0,size=0.8) +
  theme_bw()+
  theme(text = element_text(size=13),
        axis.text=element_text(colour="black"),
        panel.grid = element_blank(),
        strip.background =element_rect(fill="white",color="white"),
        legend.position = "bottom",legend.title=element_blank())

# ggsave(file="f_exp2_blocking.pdf",width = 10,height = 4)
```


```{r}
load("df.locevesim.Rda")
df.label=data.frame(trName=str_name,
                    trLabel=c("A1","A2","A3",
                              "A4","A5","A6",
                              "U1","A7","U2",
                              "A8","C2","C1",
                              "C3","C5","C4",
                              "C6","C7","C8"))
df1=df.locevesim %>% 
  summarySE(measurevar = "eve_den",groupvars =c("trName"),na.rm = T)%>% 
  mutate(eve_ci=ci)

df2=df.off %>%
  melt(id.vars=setdiff(colnames(df.off),c("blc_yn","blc_yn_ctrl","blc_yn_reset","blc_yn_other")),variable.name="blc_type",value.name = "blc")%>%
  summarySE(measurevar = "blc",groupvars =c("blc_type","trName","cyclic",'nodeNum'),na.rm = T)%>%
  mutate(blc_ci=ci)

df.blc.fig=merge(df1,df2,by=c("trName")) %>% merge(df.label,by=c("trName"))

cor.test(~eve_den+blc, subset(df.blc.fig,blc_type=="blc_yn"))
cor.test(~eve_den+blc, subset(df.blc.fig,blc_type=="blc_yn_reset"))
cor.test(~eve_den+blc, subset(df.blc.fig,blc_type=="blc_yn_ctrl"))
cor.test(~eve_den+blc, subset(df.blc.fig,blc_type=="blc_yn_other"))
```

```{r}
df.blc.fig%>%
  mutate(blc_type=factor(blc_type,levels = c("blc_yn","blc_yn_reset","blc_yn_ctrl","blc_yn_other"),labels = c("Overall","Resetting","Controlling","Other")),
        cyclic=factor(cyclic,levels = c("unconnected","acyclic","cyclic"),labels = c("Unlinked","Acyclic","Cyclic")))%>%
  mutate(nodeNum=factor(nodeNum,levels = c("3",'4'),labels = c("Three-node","Four-node")))%>%
  ggplot(aes(x=eve_den,y=blc,label=trLabel,color=nodeNum))+
  facet_wrap(~blc_type)+
  geom_point()+
  geom_errorbar(aes(ymin = blc-blc_ci,ymax = blc+blc_ci),width=0) +
  geom_errorbarh(aes(xmin = eve_den-eve_ci,xmax = eve_den+eve_ci),height=0)+
  geom_text_repel(alpha=0.3,color="black",max.overlaps =20)+
  xlab("Peak Event Density by One Random Intervention")+
  ylab("Percentage of Blocks")+
  theme_bw()+
  annotate("segment", x=-Inf, xend=Inf, y=-Inf, yend=-Inf)+
  annotate("segment", x=-Inf, xend=-Inf, y=-Inf, yend=Inf)+
  scale_colour_manual(name="Structure Nodes",values = c("black", "#FEAE00")) +
  theme(text = element_text(size=12),
        axis.text=element_text(colour="black"),
        # axis.line = element_line(color = 'black'),
        plot.background = element_blank(),
        panel.border = element_blank(),
        strip.background =element_rect(fill="white",color = "white"),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        legend.position = 'bottom')

# ggsave(file="f_exp2_blc_locevesim.pdf",width = 10,height = 7)
```
